name: Build and maybe release OVMF for timberland
on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      tag: ${{ steps.find_tag.outputs.TAG }}
    steps:
      - name: checkout sources
        uses: actions/checkout@v7
        with:
          # without fetch-deps 0, git describe fails (https://github.com/actions/checkout/pull/579)
          fetch-depth: 0
          submodules: true
      - name: set release tag from git
        id: find_tag
        # For cases where the latest changes are not to real code just the workflow
        # determine the last "real" commit
        run: |
          C=HEAD
          while ! git show --stat --pretty='' "$C" | head -n -1 | grep -q -E -v 'workflows/build.yaml|install.sh'; do
              C="$C"~ 
          done
          TAG=$(git describe --always --tags --match 'edk2-stable*' --abbrev=7 "$C")
          echo "TAG=release-$TAG" >> $GITHUB_ENV
          echo "TAG=release-$TAG" >> $GITHUB_OUTPUT
          git log -n1 --no-decorate $C >top-commit.txt
          [ "$TAG" ]
      - name: create build.sh
        run: |
          cat >build.sh <<EOF
          . ./edksetup.sh
          make -j -C BaseTools
          build -t GCC -a X64 -p OvmfPkg/OvmfPkgX64.dsc -D NETWORK_IPV6_ENABLE
          sha256sum -b Build/OvmfX64/DEBUG_GCC/FV/OVMF_CODE.fd \
              Build/OvmfX64/DEBUG_GCC/FV/OVMF_VARS.fd \
              Build/OvmfX64/DEBUG_GCC/X64/NvmeOfCli.efi \
              Build/OvmfX64/DEBUG_GCC/X64/VConfig.efi \
              > checksum.sha256
          EOF
      - name: update
        run: sudo apt-get update
      - name: install dependencies
        run: >-
          sudo apt-get install --yes
          g++ uuid-dev iasl openssl python3 unzip make
          libcunit1-dev libaio-dev libssl-dev ncurses-dev
          libjson-c-dev meson libnuma-dev autoconf automake
          libtool help2man nasm zip
      - name: build OVMF
        run: bash build.sh
      - name: create zip file
        run: >-
          zip -r timberland-ovmf-${{ env.TAG }}.zip -j
          Build/OvmfX64/DEBUG_GCC/FV/OVMF_CODE.fd
          Build/OvmfX64/DEBUG_GCC/FV/OVMF_VARS.fd
          Build/OvmfX64/DEBUG_GCC/X64/NvmeOfCli.efi
          Build/OvmfX64/DEBUG_GCC/X64/VConfig.efi
      - name: store artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ovmf-build
          path: |
            timberland-ovmf-${{ env.TAG }}.zip
            checksum.sha256
            top-commit.txt

  release:
    if: |
      ( github.ref ==
        format('refs/heads/{0}', github.event.repository.default_branch) &&
        ( github.event_name == 'push' ||
          ( github.event_name == 'pull_request' &&
            github.event.action == 'closed' &&
            github.event.pull_request.merged == true ) ) ) ||
      github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      deployments: write
      contents: write
    env:
      TAG: ${{ needs.build.outputs.tag }}
    steps:
      - name: download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: ovmf-build
      - name: check download
        run: ls -lR
      - name: create release notes
        run: |
          cat >relnotes.txt <<EOF
          ## Automated release, $(date)

          commit description: ${{ env.TAG }}
          branch: ${{ github.ref_name }}

          ### SHA256 checksums for binary artifacts:
          EOF
          sed 's/^/    /' checksum.sha256 >> relnotes.txt
          echo "### Top commit message:" >> relnotes.txt
          sed 's/^/    /' top-commit.txt >> relnotes.txt
      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          draft: false
          prerelease: false
          name: "Release ${{ env.TAG }}"
          tag_name: "${{ env.TAG }}"
          body_path: relnotes.txt
          files: timberland-ovmf-${{ env.TAG }}.zip
